Main/urls.py
from django.urls import path

from . import views

app_name = 'Main'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact_submit/', views.contact_submit, name='contact_submit'),
    path('<int:msg_sent_bool>', views.index, name='contact_submitted'),
]

RenanPortfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('FE_project/', include('FE_project.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Main/models.py
#from django.db import models

Main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from string import Template
import requests
from django.conf import settings


def index(request,msg_sent_bool=0):
    projects = ProjectsList()
    projects += [ProjectItem("Finite Element Analysis Web App",
                          "Web application with 3D configuration on the client-side and numeric calculations on the serve-side",
                          ["python-logo.png","coffeescript.png","javascript.png","django.png",
                           "ajax.png","seen.png","jQuery.png"],
                          "FEproject.png",
                          "FE_project", True)]
    projects += [ProjectItem("Sight Reading Trainner Web App",
                             "Java web application running with no need for support on the browser.",
                             ["java.png","maven.png","jpro.png","jfugue.png",
                              "docker.png"],
                             "sightreading.PNG",
                             "https://sight-reading-trainer-webapp.herokuapp.com/", True)]
    projects += [ProjectItem("Duolingo Chrome Extension",
                             "Chrome extension for adding sentence related pictures to the Duolingo app.",
                             ["javascript.png","react.jpg","html.png","chrome.png"],
                             "Duolingo.png",
                             "https://github.com/siqueirarenan/Duolingo_Pic")]
    projects += [ProjectItem("Topology Optimization Plug-in",
                             "Plug-in to run a self-developed topology optimization method in Abaqus CAE.",
                             ["python-logo.png","abaqus.png"],
                             "IZEOabaqus2.png",
                             "https://github.com/siqueirarenan/IZEO_Topology_optimization_Abaqus_script")]
    projects += [ProjectItem("COVID-19 Data Analysis",
                             "In-development database and UI for analysis of COVID-19 statistics.",
                             ["python-logo.png","django.png","react.jpg","mysql.jpg","restapi.png"],
                             None,
                             "https://github.com/siqueirarenan/Coronavirus-data-analysis")]

    context = {'msg_sent_bool': str(msg_sent_bool),
               'projects' : projects}
    return render(request,'Main/index.html',context)


def contact_submit(request):

    v_name = request.GET['Name']
    v_email = request.GET['Email']
    v_subject = request.GET['Subject']
    v_comment = request.GET['Comment']

    message_template = Template("PORTFOLIO CONTACT FORM\n\nName: ${NAME}\nEmail: ${EMAIL}\nSubject: ${SUBJECT}\n\nMessage:\n\n${MESSAGE}\n--")

    message = message_template.substitute(NAME=v_name,EMAIL=v_email,SUBJECT=v_subject,MESSAGE=v_comment)

    f = open(settings.BASE_DIR / "Main/credentials.txt",'rt')
    mailgun = f.readlines()
    f.close()

    resp = requests.post(mailgun[0][0:-1],auth=("api", mailgun[1][0:-1]),data={"from": mailgun[2],"to": ["renansiqueira@gmail.com"],"subject": "Portfolio Contact Form - " + v_subject,"text": message})

    if resp.status_code == 200:
        return HttpResponseRedirect("/1#contact")
    else:
        return HttpResponseRedirect("/2#contact")


class ProjectItem:
    def __init__(self, name, text, tools, main_pic, href, tryYourself=False):
        self.name = name
        self.text = text
        self.tools = tools
        self.mainPic = main_pic
        self.href = href
        self.tryYourself = tryYourself

class ProjectsList:
    def __init__(self):
        self.elements = []

    def __getitem__(self, item):
        return self.elements[item]

    def __add__(self, other):
        assert (isinstance(other[0], ProjectItem))
        self.elements += other

        return self

    def __len__(self):
        return len(self.elements)

Main/templates/Main/index.html
<!DOCTYPE html>
<html>
<title>Renan Siqueira - Portfolio</title>

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-7QKVD00XR3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-7QKVD00XR3');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'FE_project/mainCSS.css'%}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}"/>
</head>
<body style="background-color:#ECECEC">

<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-wide w3-padding w3-card">
    <a href="#home" class="w3-bar-item w3-button">Renan Siqueira <b>Portfolio</b></a>
    <!-- Float links to the right. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="#projects" class="w3-bar-item w3-button">Projects</a>
      <a href="#about" class="w3-bar-item w3-button ">About</a>
      <a href="#contact" class="w3-bar-item w3-button w3-hide-medium">Contact</a>
    </div>
  </div>
</div>

<!-- Header -->
<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
    <div class="paralaxPic" style="background-image: url({% static 'pictures/top_pic.JPG' %});height: 650px;"></div>
  <div class="w3-display-left w3-margin-top w3-margin-left w3-left">
    <h1 class="w3-xxxlarge w3-text-white w3-margin-left w3-margin-bottom">
      <span class="w3-hide-medium w3-hide-large center w3-black w3-opacity-min"><b>Renan Siqueira</b> Ph.D.</span>
      <span class="w3-hide-small w3-padding w3-black w3-opacity-min"><b>Renan Siqueira</b> Ph.D.<br></span>
      <span class="w3-hide-small w3-white w3-opacity-min w3-text-black">Software Development Engineer<br></span>
    <span class="w3-hide-small "><b></b><br></span>
    <span class="w3-hide-small "><b></b><br></span>
    <span class="w3-hide-small "><b></b><br></span>
    </h1>
  </div>
</header>

<!-- Page content -->
<div class="w3-content" style="max-width:1100px">
    <!-- Project Section -->
    <div class="w3-container  w3-padding" id="projects">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Projects</h3>
    </div>
    {% for project in projects %}
        <a href="{{project.href}}">
            <div class="w3-card w3-white">
                <div class="w3-container w3-black w3-text-white">
                    <h2 class="">{{project.name}}</h2>
                </div>
                <div class="w3-container w3-text-black ">
                    <h5>{{project.text}}</h5>
                    <div class="w3-padding" style="text-align:right">
                        {% for tool in project.tools %}
                        <img src="{% static 'pictures/'%}{{tool}}" class="PaddingSides" style="width:100px;padding-bottom:16px">
                        {% endfor %}
                    </div>
                </div>
                {% if project.tryYourself %}
                <span>
                    <div class="w3-large w3-tag w3-round w3-indigo w3-padding-16 PaddingSides MarginSides">Try yourself!</div>
                </span>
                {% endif %}
            </div>
        </a>
        {% if project.mainPic %}
        <div class="paralaxPic" style="background-image: url({% static 'pictures/'%}{{project.mainPic}});filter: contrast(85%);"></div>
        {% endif %}
    {% endfor %}

  <!-- About Section -->
  <div class="w3-container w3-padding-32 " id="about">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">About</h3>

    <div class="w3-container" style="justify-content: center" >
      <div class="w3-row-padding">
          <div class="w3-col l3 m4 s12">
            <img class="w3-padding" src="{% static 'pictures/MyPic.jpg'%}" alt="John" style="max-height:300px;width:auto">
          </div>
          <div class="w3-col l9 m12 s12">
            <p>Renan Siqueira is a Ph.D. in product development and programmer enthusiast. During his career he
              worked in Brazil, USA, Germany and Australia, while actuating in diverse fields, such as mechatronics, oil industry,
                optimization and development research. In spite of that, the link between all these experiences lies in
                software development, a passion that comes to be a solution for all kinds of problems.
            </p>
            <h3 class="w3-padding w3-serif" style="margin:auto">
              <i>"I love to learn and solve new challenges!"</i>
            </h3>
          </div>

      <span id="socialNetworks">
          <a href="https://www.researchgate.net/profile/Renan_Siqueira5" target="_blank">
              <img src="{% static 'pictures/researchG.png' %}"></a>
          <a href="https://www.linkedin.com/in/siqueira-renan/" target="_blank">
            <img src="{% static 'pictures/Linkedin-Icon.png' %}"></a>
          <a href="https://github.com/siqueirarenan" target="_blank">
            <img src="{% static 'pictures/git.png' %}"></a>
<!--          <a href="https://www.scrum.org/certificates/582761" target="_blank">-->
<!--            <img src="" style="padding: 10px; float: right;width:5%;min-width:85px;height:auto;"></a>-->
      </span>
      </div>
    </div>
    </div>

  <!-- Contact Section -->
  <div class="w3-container w3-padding-32" id="contact">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Contact</h3>
    <p>Please, get in touch if you have any enquiry.</p>
<!--    <a href="mailto:renansiqueira@gmail.com?subject=Website Enquiry" >renansiqueira@gmail.com</a>-->

       <form action="{% url 'Main:contact_submit' %}" method="get">  <!-- tag url call function from Main.urls-file by its "name", with the urls adress parameters -->

          <input class="w3-input w3-border" type="text" placeholder="Name" required name="Name" value="{{ v_name }}">
          <input class="w3-input w3-section w3-border" type="text" placeholder="Email" required name="Email" value="{{ v_email }}">
          <input class="w3-input w3-section w3-border" type="text" placeholder="Subject" required name="Subject" value="{{ v_subject }}">
          <input class="w3-input w3-section w3-border" type="text" placeholder="Comment" required name="Comment" value="{{ v_comment }}">
          {% if msg_sent_bool == "0" %}
          <button class="w3-button w3-black w3-section" type="submit">SEND MESSAGE</button>
          {% endif %}
          {% if msg_sent_bool == "1" %}
            <div class="w3-text-grey"> <p> SENT </p> </div>
          {% endif %}
          {% if msg_sent_bool == "2" %}
            <div class="w3-text-red"> <p> I'm sorry, there is a problem with the server. Please send your message directly to renansiqueira@gmail.com </p> </div>
          {% endif %}
        </form>
  </div>

  </div>





<!-- End page content -->


<!-- Image of location/map -->
<div  style="width:100%">
  <img src="{% static 'pictures/bottom_pic.JPG'%}" style="object-fit: cover;width:100%;height=50%;" >
</div>

<!-- Footer -->
<footer class="w3-center w3-black w3-padding-16">
  <p>Template by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-text-green">W3</a>. Designed using Django by Renan Siqueira.</p>
</footer>


</body>
</html>